name: Run unit tests for hello_world lambda function script

on:
  # Trigger the workflow for pull requests
  pull_request:
    types: [opened, edited, reopened, synchronize]

  # Trigger the workflow for pushes to the "main" branch
  push:
    branches:
      - 'main'

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust based on the Python version you're using

      - name: Install pytest-cov
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest --cov=hello_world --cov-report=term-missing ./lambda_function_files/hello_world/test_hello_world.py
